Implementar code testing
GCastilho/unip-tcc pull request #11
Opened 2019-10-07 14:43 UTC by GCastilho

-- Adicionar unit tests do login de usuários (/login)
-- Adicionar unit tests do signUp de usuários (/register)
-- Adicionar unit tests na CurrencyApi
-- Mover currencyApi de /api/currency para /currencyApi
-- Roteamento para subdiretórios ser feito por um módulo 'router', e o conteúdo desses subdiretórios ficar hierarquicamente nessa mesma pasta router
-- Atualizar dependências para a última versão
-- Criar arquivo para armazenar as variáveis de ambiente do ambiente de desenvolvimento e de teste

2019-10-08 19:11 UTC, joaojvds requested changes
Renomeie a pasta onde você coloca os tests para _ _ tests _ _ , ou então coloque os arquivos test.js junto com os arquivos que você estar testando, essa é convenção que o jest usa.

2019-10-08 20:08 UTC, GCastilho commented
Eu não vi essa convenção de chamar a pasta com os testes de "__tests__" em nenhum lugar, onde vc viu essa informação?

2019-10-08 20:16 UTC, joaojvds commented
Vi isso no github do jest, quando ele inicia ele procura por essa pasta, se ele não achar a pasta ele procura por arquivos .test.js. Dentro dessa pasta os arquivos não precisam ter o .test, pois o jest já reconhece os arquivos dentro dela como arquivos de teste

2019-10-08 20:34 UTC, GCastilho commented
Bom, então não é uma boa ideia, pois nem todos os arquivos daquela pasta são arquivos de teste, tem arquivos de configuração de pretest e outros que são executados por um teste em ordem

Se esse é o comportamento de uma pasta __test__ é incompatível com o estado atual do código

2019-10-09 23:31 UTC, joaojvds approved these changes

2019-10-09 23:38 UTC, merged