Adicionado valor mínimo para saque
GCastilho/unip-tcc pull request #62
Opened 2020-04-05 22:37 UTC by joaojvds

--Fix issue #57
--Adicionado texto informando qual é o limite mínimo de saque
--Adicionado check para impedir valor de saque abaixo do limite do fee
--Implementar limite de saque no backend

2020-04-14 19:02 UTC, GCastilho commented
Precisa fazer os testes, eu não sei quando vou ter tempo, Quer se aventurar e começar eles, @joaojvds? Posso ir te guiando no _que_ precisa ser testado

2020-04-27 23:06 UTC, GCastilho requested changes
Vc não mudou o botão de lugar como eu disse
e quebrou os comentários do teste

2020-04-27 23:06 UTC, GCastilho commented on tests/CurrencyApi/operations.test.ts
> +
Coloca esse teste no final do arquivo, pq ele foi adicionado por último

2020-04-27 23:06 UTC, GCastilho commented on tests/CurrencyApi/operations.test.ts
> +					*/
Corrige a indentação desse comment

2020-04-27 23:06 UTC, GCastilho commented on tests/CurrencyApi/operations.test.ts
> +					*/
Desse tbm

2020-04-27 23:06 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
Isso daqui tira o botão de withdraw do lado direito. O botão de withdraw deve ficar do lado direito com o texto

2020-04-27 23:06 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		text-align: right
Não há a necessidade desse p ter text-align pois o form terá o text-align para a direita

2020-04-28 17:21 UTC, joaojvds commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
se eu usar usar essa linha TODO texto sera alinhado para a direita incluindo o texto de erro, que eu quero que seja centralizado, mas eu já alterei o css para que o botão fique onde você quer.

2020-04-28 17:28 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
Coloca o texto do erro centralizado, ué. "Todo o form está para a direita exceto esse erro"
É pra isso que serve o "Cascade" do CSS

2020-04-28 17:35 UTC, joaojvds commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
e você acha que eu não tentei alinhar somente o texto do erro?

2020-04-28 17:36 UTC, GCastilho requested changes
Tira o flex do form, alinha para a direita e a mensagem de erro vc centraliza. Keep Things Simple

2020-04-28 17:36 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		flex-direction: column;
Explica pra mim, pq vc teve que botar um flex aqui?

2020-04-28 17:36 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		height: 45px;
Isso n tava aqui antes, pq vc mudou o tamanho do botão?

2020-04-28 17:36 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		align-self: flex-end;
Overengineering no CSS do botão

2020-04-28 17:37 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
Tu ta dizendo que não tem como dar override nisso?

2020-04-28 17:41 UTC, joaojvds commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		flex-direction: column;
eu não estava conseguindo mudar a posição do botão pelo display block, então eu mudei para um mais livre de eu alterar

2020-04-28 17:42 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> -		text-align: right;
Aliás, eu acabei de ver aqui. Não ficou ruim a mensagem de erro do lado direito. Vc REALMENTE acha necessário que ela seja centralizada?
Eu acho que se encaixa ela estar à direita

2020-04-28 17:44 UTC, joaojvds commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		align-self: flex-end;
ele esta se alinhando para a direita e é um comando bem comum, eu simplesmente usei uma propriedade do flexbox se mudar para direita também vai

2020-04-28 17:48 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		flex-direction: column;
Entendi. Sem problemas
Mas faz do jeito q eu falei por whats, deixa o forma com tet-align para a direita e _se quiser_ centraliza a msg de erro com display block e text-align

2020-04-28 17:49 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		align-self: flex-end;
Saquei

2020-04-28 17:54 UTC, joaojvds commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		height: 45px;
Eu preferi deixar o tamanho do botão setado para evitar que se deforme em alguma outra resolução, fora que esse botão é para ter um tamanho fixo

2020-04-28 18:20 UTC, GCastilho commented on client/src/routes/balances/_tableRow/withdrawCell.svelte
> +		height: 45px;
Tem como a resolução dele deformar assim? Eita

2020-04-28 18:30 UTC, GCastilho approved these changes
Pode fazer o commit, **usa a mensagem do PR** (eu editei ela)

2020-04-28 18:35 UTC, merged