Mensagem de erro da pagina login
GCastilho/unip-tcc pull request #8
Opened 2019-09-15 02:05 UTC by joaojvds

--Adicionado mensagem de erro ao digitar um login incorreto 
--fixes #5 
--Removido lixo do código

2019-09-19 03:14 UTC, GCastilho commented on client/public/index.html
> -        <noscript>You need to enable JavaScript to run this app.</noscript>
Pq tirar essa linha?

2019-09-20 00:11 UTC, joaojvds commented on client/public/index.html
> -        <noscript>You need to enable JavaScript to run this app.</noscript>
Percebi que era melhor mesmo deixar essa linha, então coloquei de volta

2019-09-28 03:25 UTC, GCastilho requested changes
Algumas modificações pontuais no código descritas nominalmente e um detalhe relevante:

É necessário atualizar o react-script por uma vulnerabilidade, então rode um 'npm audit fix' ('npm audit' pra detalhes) no cliente/frontend/react para ele atualizar as dependências dos arquivos package.json e é pra estar tudo certo

2019-09-28 03:25 UTC, GCastilho commented on client/src/pages/login/Login.css
> +    color: crimson;
o contraste entre a background color e a cor do texto tá muito baixo (é meio difícil de ler), dá uma melhorada nisso

2019-09-28 03:25 UTC, GCastilho commented on client/src/pages/register/Register.jsx
> +        }*/ else {
Tira esses checks não usados, se/quando formos fazer esse tipo de check, o servidor irá fazê-lo e retornar a errorMsg adequada (o cliente apenas irá inseri-la na tela), não sendo necessário ter esse check no cliente, ou esse código pra adicionar depois (pq não vai adicionar anyway)

2019-09-28 03:25 UTC, GCastilho commented on client/src/pages/register/Register.jsx
> +                        <h1>Quase lá</h1>
Troca essa mensagem para algo mais "formal" tipo "Confirme o email" ou "necessário confirmar/confirmação de email", algo do tipo, mas tira esse "quase lá" daí, pq além de estranho ele faz parecer que a conta não foi _criada_, o que ela foi

2019-09-28 03:25 UTC, GCastilho commented on client/src/pages/register/Register.jsx
> +                        <p>O email <b>{this.state.email}</b> esta correto ?</p>
E troca essa mensagem pra uma msg mais adequada tbm, tipo "enviamos um email de confirmação de cadastro para <email>, para ativar sua conta por favor siga as instruções informadas no email" ou algo disso tipo (não precis ser _essa_ mensagem nem nada, é uma sugestão)

2019-09-28 16:44 UTC, joaojvds commented on client/src/pages/register/Register.jsx
> +        }*/ else {
Apaguei os checks de senha da pagina

2019-09-28 17:49 UTC, joaojvds commented on client/src/pages/login/Login.css
> +    color: crimson;
Mudei as tonalidades de vermelho da mensagem de erro

2019-09-28 20:57 UTC, GCastilho commented on client/src/index.js
> +import Routes from './routes';
Pq mesmo vc voltou pra o que tava antes?

2019-09-28 21:00 UTC, joaojvds commented on client/src/index.js
> +import Routes from './routes';
pq essa pagina é carregada junto com o react e não faz diferença no tempo de carregamento

2019-09-28 22:16 UTC, GCastilho approved these changes
Digamos que ficou realmente bom e mais otimizado que antes, parabéns

2019-09-28 22:17 UTC, merged